# VyOS build for gerneric qemu/kvm environments like proxmox. 
# Includes "qemu-guest-agent" to improve interoperability with different cloud environments
image_format = "qcow2"
packages=["qemu-guest-agent"]
