# vyos build for gerneric qemu/kvm environments like proxmox. 
# Includes "qemu-guest-agent" to improve interoperability with different cloud environments and "cloud-init" (see: https://docs.vyos.io/en/latest/automation/cloud-init.html and https://docs.vyos.io/en/latest/automation/cloud-init.html#prepare-cloud-init-files)
image_format = "qcow2"
packages=["qemu-guest-agent", "cloud-init"]
